# Generated by Django 3.2.16 on 2024-11-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_candidate', models.CharField(choices=[('CA', 'кандидат'), ('WR', 'сотрудник')], default='CA', help_text='Статус', max_length=2)),
                ('first_name', models.CharField(help_text='Имя', max_length=50)),
                ('last_name', models.CharField(help_text='Фамилия', max_length=50)),
                ('location', models.CharField(help_text='Город/населенный пункт', max_length=50)),
                ('email', models.EmailField(help_text='Электронный адрес', max_length=100)),
                ('phone', models.CharField(help_text='Номер телефона', max_length=15)),
                ('general_skills', models.TextField(help_text='Основные навыки')),
                ('birthday', models.DateField(help_text='Дата рождения')),
                ('zodiac_sign', models.CharField(help_text='Знак зодиака', max_length=15)),
                ('age', models.IntegerField(help_text='Возраст')),
                ('significator', models.IntegerField(help_text='Сигнификатор')),
                ('court_card', models.IntegerField(help_text='Придворная карта')),
            ],
        ),
    ]
