# Generated by Django 4.2.9 on 2024-11-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.IntegerField(help_text="Возраст", verbose_name="Возраст"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="birthday",
            field=models.DateField(
                help_text="Дата рождения", verbose_name="Дата рождения"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="court_card",
            field=models.IntegerField(
                help_text="Придворная карта", verbose_name="Придворная карта"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                help_text="Электронный адрес",
                max_length=100,
                verbose_name="mail@example.com",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(help_text="Имя", max_length=50, verbose_name="Иван"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="general_skills",
            field=models.TextField(
                help_text="Основные навыки", verbose_name="Укажите основные навыки"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_candidate",
            field=models.CharField(
                choices=[("CA", "Кандидат"), ("WR", "Сотрудник")],
                default="CA",
                help_text="Статус",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(
                help_text="Фамилия", max_length=50, verbose_name="Иванов"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="location",
            field=models.CharField(
                help_text="Город/населенный пункт", max_length=50, verbose_name="Москва"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                help_text="Номер телефона",
                max_length=15,
                verbose_name="+7 999 999 99 99",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="significator",
            field=models.IntegerField(
                help_text="Сигнификатор", verbose_name="Сигнификатор"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="zodiac_sign",
            field=models.CharField(
                help_text="Знак зодиака", max_length=15, verbose_name="Знак зодиака"
            ),
        ),
    ]
